${EE_SIDE_PREFIX}_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - ${EE_SIDE_PREFIX}_right_finger_joint
      - ${EE_SIDE_PREFIX}_left_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0
      ${EE_SIDE_PREFIX}_right_finger_joint:
        goal: 0.02
      ${EE_SIDE_PREFIX}_left_finger_joint:
        goal: 0.02
